# Generated by Django 2.2 on 2019-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='semana_alquila',
            field=models.DateField(default='1990-11-11'),
            preserve_default=False,
        ),
    ]
