# Generated by Django 2.2.2 on 2019-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquila',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
