# Generated by Django 2.2.1 on 2019-06-09 13:08

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_tarjeta',
            field=creditcards.models.SecurityCodeField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_tarjeta',
            field=creditcards.models.CardNumberField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vencimiento_tarjeta',
            field=creditcards.models.CardExpiryField(blank=True, null=True),
        ),
    ]
