# Generated by Django 2.1.7 on 2019-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20190518_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='monto_actual',
            field=models.FloatField(default=0.0),
        ),
    ]
