# Generated by Django 2.1.7 on 2019-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20190504_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='foto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
