# Generated by Django 2.1.7 on 2019-05-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20190519_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='monto_inicial',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creditos',
            field=models.IntegerField(default=2),
        ),
    ]
