# Generated by Django 2.2.1 on 2019-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_auto_20190522_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables_sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_usuario_comun', models.FloatField(default=0.0)),
                ('precio_usuario_premium', models.FloatField(default=0.0)),
            ],
        ),
    ]
