# Generated by Django 2.1.7 on 2019-05-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_auto_20190504_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='codigo_subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Subasta'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='codigo_residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Residencia'),
        ),
    ]
