# Generated by Django 2.1.7 on 2019-05-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_auto_20190504_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.FloatField()),
                ('codigo_residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Residencia')),
                ('email_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Usuario')),
            ],
        ),
    ]
