# Generated by Django 2.1.7 on 2019-05-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_residencia_borrado_logico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='foto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name=models.AutoField(primary_key=True, serialize=False)),
        ),
    ]
