# Generated by Django 2.1.7 on 2019-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0012_auto_20190504_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='patito',
        ),
        migrations.AddField(
            model_name='residencia',
            name='foto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='patito'),
        ),
    ]
