# Generated by Django 2.1.7 on 2019-05-05 00:26

from django.db import migrations, models
import modelos.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0015_auto_20190504_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='foto',
            field=models.FileField(blank=True, default=None, null=True, upload_to=modelos.models.get_file_path),
        ),
    ]
