# Generated by Django 2.1.7 on 2019-05-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0016_auto_20190504_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='ubicacion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
