from modelos.models import (Usuario)
u = Usuario(username='osvaldo.mantecovich@gmail.com')
u.set_password('123')
u.is_superuser = True
u.is_staff = True
u.nombre = ("Osvaldo")
u.apellido = ("Mantecovich")
u.email = ('osvaldo.mantecovich@gmail.com')
u.fecha_nacimiento = ("1987-3-22")
u.creditos = (2)
u.type = ("admin")
u.save()
us = Usuario(username='sebastia.villena@gmail.com')
us.set_password('123')
us.is_superuser = False
us.is_staff = False
us.is_active = True
us.nombre = ("Sebastian")
us.apellido = ("Villena")
us.email = ("sebastia.villena@gmail.com")
us.fecha_nacimiento = ("1997-13-12")
us.numero_tarjeta = ("4830806605707486")
us.vencimiento_tarjeta("25-10-01")
us.codigo_tarjeta(902)
us.creditos = (2)
us.type = ("premium")
us.save()
use = Usuario(username='rociobrindesi@gmail.com')
use.set_password('123')
use.is_superuser = False
use.is_staff = False
use.nombre = ("Roro")
use.apellido = ("Brindesi")
use.email = ("rociobrindesi@gmail.com")
use.fecha_nacimiento = ("1998-6-27")
use.numero_tarjeta = (5574842721834331)
use.vencimiento_tarjeta("02-22")
use.codigo_tarjeta(582)
use.creditos = (2)
use.type = ("comun")
use.save()
user = Usuario(username='brunodg91@gmail.com')
user.set_password('123')
user.is_superuser = False
user.is_staff = False
user.nombre = ("Bruno")
user.apellido = ("Garcia")
user.email = ("brunodg91@gmail.com")
user.fecha_nacimiento = ("1991-01-27")
user.numero_tarjeta = (4004442535586012)
user.vencimiento_tarjeta("02-24")
user.codigo_tarjeta(643)
user.creditos = (2)
user.type = ("comun")
user.save()
uuser = Usuario(username='michi@gmail.com')
uuser.set_password('123')
uuser.is_superuser = False
uuser.is_staff = False
uuser.nombre = ("michi")
uuser.apellido = ("michifus")
uuser.email = ("michi@gmail.com")
uuser.fecha_nacimiento = ("2000-01-27")
uuser.numero_tarjeta = (4647825126886283)
uuser.vencimiento_tarjeta("11-24")
uuser.codigo_tarjeta(670)
uuser.creditos = (2)
uuser.type = ("premium")
uuser.save()