# Generated by Django 2.2 on 2019-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_itemscatalogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsCatalogo',
        ),
    ]
